name: Test & Deploy Dev

on:
  push:
    branches:
      - master

jobs:

  deploy-lambda:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ github.sha }}
        run: echo "$GITHUB_CONTEXT"
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: NPM install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Create tar gz file
        run:  tar --exclude *.terraform* -zcvf build.tar.gz build infrastructure

      - name: Send run to Terraform Cloud
        uses: addresscloud/terraform-cloud-action@master
        with:
          tfToken: ${{ secrets.TERRAFORM_TOKEN }}
          tfOrg: 'Addresscloud'
          tfWorkspace: 'hello-world-terraform'
          filePath: './build.tar.gz'

          